services:
  mongodb-dev:
    container_name: mongodb-dev
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=meyfer_admin
      - MONGO_INITDB_ROOT_PASSWORD=meyfer_secret
      - MONGO_INITDB_DATABASE=meyfer_dev
    networks:
      - meyfer-network

networks:
  meyfer-network:
    driver: bridge

volumes:
  mongodb_data_dev: